wordpress:
  hosts:
    wp_server:
      ansible_host: "{{ wordpress_ip }}"
      ansible_port: 22
      ansible_user: ubuntu
      ansible_ssh_private_key_file: "{{ private_key_path }}"
      ansible_ssh_common_args: "-o IdentitiesOnly=yes"
